.github/workflows/aks-deploy.yaml

No longer using github action for kubernetes generic secrets.

Secrets fix

---

.github/workflows/aks-deploy-ui.yaml

Add a new workflow file for use with UI deployments that utilizes GitHub environments.
Aside from autoformatting updates, this is the only relevant change from aks-deploy.yaml:
Closes #2

add a workflow specifically for ui deploys to use github's environments

---

.github/workflows/aks-deploy-ui.yaml
.github/workflows/aks-deploy.yaml
.gitignore

Merging custom GoComics deploy workflow into main after making minor updates.

MERGE-STORY/DT-563/AB-ENVIRONMENT

---

.github/workflows/aks-deploy.yaml

- Fixing bugs in 1.6 release
- Minor structural/naming changes
- Resolved the set-output deprecation warnings

[DT-481] fix-1.6-release

---

.github/workflows/b2c-build-and-deploy.yaml

Adding Azure B2C auth build & deploy reusable workflow

[DEVOPS] add-b2c-workflow

---

.github/workflows/aks-deploy.yaml

Bump azure/k8s-bake action from v2.2 to v2.4

Bump k8s-bake from v2.2 to v2.4

---

.github/workflows/wpe-deploy.yaml

- Added WP Engine deployment workflow
N/A

[DEVOPS] add wpe deploy workflow

---

.github/workflows/lint-and-format.yaml

Add mega linter

---

.gitattributes
.github/.templatesyncignore
.github/CODEOWNERS
.github/dependabot.yml
.github/labeler.yml
.github/workflows/codeowners-validation.yaml
.github/workflows/jira-lint.yaml
.github/workflows/mega-lint.yaml
.github/workflows/pr-clean-caches.yaml
.github/workflows/pr-labels.yaml
.github/workflows/simple-lint.yaml
.github/workflows/template-sync.yaml
.gitignore
.prettierignore
README.md

- Set up template syncing
- Manually sync'd files with `.github` repository
- Updated README to look prettier and more organized
- Updated workflow triggers that we want to trigger on a PR in this repository.
N/A

[DEVOPS] set up template syncing

---

.github/workflows/azfunction-deploy.yaml
README.md

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/GOCOMICS-1224" title="GOCOMICS-1224" target="_blank">GOCOMICS-1224</a></summary>
<br />
<table>
<tr>
<td>[DEVOPS] Build out reusable pipeline to integrate GitHub and Azure Functions</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td><a href="https://amuniversal.atlassian.net/issues?jql=project%20%3D%20GOCOMICS%20AND%20labels%20%3D%20DiscussinPMMeeting%20ORDER%20BY%20created%20DESC" title="DiscussinPMMeeting">DiscussinPMMeeting</a>, <a href="https://amuniversal.atlassian.net/issues?jql=project%20%3D%20GOCOMICS%20AND%20labels%20%3D%20DiscussinProdSupportMeeting%20ORDER%20BY%20created%20DES …

[GOCOMICS-1224] add reusable azure function deploy

---

.github/workflows/update-game-config.yaml
.github/workflows/update-game-config.yml

- Add game config update workflow

[DEVOPS] Add game config update workflow

---

.gitignore

Merge Andrews-McMeel-Universal/.github 5b60e66

🔄 Sync with @Andrews-McMeel-Universal/.github

---

.github/workflows/ruby-ci.yaml

- Simplified Ruby on Rails Application CI 
- Added step names
- Removed BUNDLER_VERSION variable
- Fixed INSTALL_NODE variable
- Changed setup Ruby step to use latest v1 release
- Switched to using `ubuntu-latest` instead of `ubuntu-20.04` for the `runs-on` option.
- Successful run: [![PR Checks](https://github.com/Andrews-McMeel-Universal/gocomics/actions/workflows/pr-checks.yml/badge.svg?branch=DEVOPS-xxx-add-app-ci)](https://github.com/Andrews-McMeel-Universal/gocomics/actions/workflows/pr-checks.yml)

[DEVOPS-XXX] Simplify Ruby CI

---

.github/workflows/update-game-config.yaml

Fixing game config deploy workflow by adding quotes around `Update-CloudGameConfigs.ps1` arguments

Fixing Game Config Deploy Workflow

---

.github/workflows/docker-ci.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/PUZSOC-5543" title="PUZSOC-5543" target="_blank">PUZSOC-5543</a></summary>
<br />
<table>
<tr>
<td>Fix Application CI build issues in latest Hex10 updates PR</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Removing problematic volume mount in `docker-run-action` step
- Jira Issue: [PUZSOC-5543](https://amuniversal.atlassian.net/browse/PUZSOC-5543)
- Working test: [![PR Checks](https://github.com/Andrews-McMeel-Universal/hex-10_game/actions/workflows/pr-checks.yml/badge.svg?branch=PUZSOC-5543-fix-docker-build)](https://github.com/Andrews-McMeel-Un …

[PUZSOC-5543] Fix Hex 10 Application CI tests failing

---

.github/workflows/aks-deploy.yaml
.github/workflows/dependabot-automations.yaml
.github/workflows/mega-lint.yaml
.github/workflows/purge-cdn.yaml
.github/workflows/template-sync.yml
.github/workflows/update-addns.yaml
.github/workflows/update-azureapimanagement.yaml
.github/workflows/wpe-deploy.yaml

- Switching to major release tags for GitHub actions

[DEVOPS-XXX] Switch to major release tags for GitHub Actions

---

.github/workflows/aks-deploy.yaml
.github/workflows/azfunction-deploy.yaml
.github/workflows/b2c-build-and-deploy.yaml
.github/workflows/dotnet-ci.yaml
.github/workflows/next-ci.yaml
.github/workflows/purge-cdn.yaml
.github/workflows/ruby-ci.yaml
.github/workflows/update-azureapimanagement.yaml
.github/workflows/update-game-config.yaml

- Switching over to new [cache-azure-login](https://github.com/Andrews-McMeel-Universal/cache-azure-login) GitHub Action
- Testing Environment: [![Test Azure Login Action](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/test-azure-login.yml/badge.svg)](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/test-azure-login.yml)

[DEVOPS-XXX] Switching over to new cache-azure-login action

---

.github/workflows/aks-deploy.yaml

- Revert back to `azure/login` action in deploy job in the `aks-deploy.yaml` workflow to fix bug with the `Azure/aks-set-context` action

[DEVOPS-XXX] Fix aks-set-context bug with azure/login action

---

.github/workflows/ui-ci.yaml

- Created a duplicate of `next-ci.yaml` to create `ui-ci.yaml` that accounts for the v3 Yarn install.
- Jira Issue: DEVOPS-241

[DEVOPS-241] Add new UI CI workflow

---

.github/workflows/aks-deploy.yaml

- Converted PowerShell scripts into bash scripts to speed up AKS deploy run times
- Removed redundant Cache Azure Login steps in favor of `get-envs` nested cache-azure-login action
- Jira Issue: DEVOPS-270
- Test environment: [![Development AKS Deploy](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/aks-development.yml/badge.svg?branch=story%2FDEVOPS-270%2Fimprove-aks-deployment-run-times)](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/aks-development.yml)

[DEVOPS-270] Improve run times by switching to bash scripts

---

.github/workflows/simple-lint.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-280" title="DEVOPS-280" target="_blank">DEVOPS-280</a></summary>
<br />
<table>
<tr>
<td>Update prettier action in Simple Lint workflow to v3</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Upgrade prettier action to v3 in Simple Lint workflow
- Jira Issue: DEVOPS-280

[DEVOPS-280] Upgrade prettier action

---

.github/workflows/b2c-ci.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-287" title="DEVOPS-287" target="_blank">DEVOPS-287</a></summary>
<br />
<table>
<tr>
<td>Add B2C CI reusable workflow</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add B2C Application CI workflow
- Jira Issue: DEVOPS-287

[DEVOPS-287] Add B2C Application CI workflow

---

.github/workflows/ephemeral-deploy.yaml
.github/workflows/jira-lint.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-298" title="DEVOPS-298" target="_blank">DEVOPS-298</a></summary>
<br />
<table>
<tr>
<td>Fix Jira Linter regex match failures</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>New</td>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Make PR branch and title regex match report back true if no match is found.
- Jira Issue: DEVOPS-298

[DEVOPS-298] Fix Jira Linter regex match failures

---

.github/workflows/ephemeral-deploy.yaml

- Set timeout on deploy steps in Ephemeral Deployment workflow to avoid deploy jobs running indefinitely.

[DEVOPS-XXX] Set timeout on deploy steps in Ephemeral Deployment workflow

---

.github/workflows/ephemeral-deploy.yaml

- Moved Next.js steps to update-next-deploy job in Ephemeral Deployment workflow

Moved Next.js steps to update-next-deploy job in Ephemeral Deployment workflow

---

.github/workflows/publish-nuget-package.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-291" title="DEVOPS-291" target="_blank">DEVOPS-291</a></summary>
<br />
<table>
<tr>
<td>Create reusable workflow from Nuget increment version scripts</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add Publish Nuget Package workflow
- Jira Issue: DEVOPS-291

[DEVOPS-291] Add Publish Nuget Package workflow

---

.github/workflows/ephemeral-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-304" title="DEVOPS-304" target="_blank">DEVOPS-304</a></summary>
<br />
<table>
<tr>
<td>Use checkboxes in the PR description to determine the ephemeral deployment's APIs</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Determine which environment key vault to use based off of what environment is checked off in the PR description.
- Removed `environment` input
- Replaced `environmentKeyVault` input with `environmentKeyVaultPrefix` input that defaults to the repository's `${{ vars.AZURE_KEYVAULT_PREFIX }}` variable
- Jira Issue: DEVOPS-304 …

[DEVOPS-304] Determine ephemeral deployment environment key vault to use based off PR description

---

.github/workflows/ephemeral-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-303" title="DEVOPS-303" target="_blank">DEVOPS-303</a></summary>
<br />
<table>
<tr>
<td>Post environment details to ephemeral deployments comment in Jira ticket</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add ephemeral deployment environment details when posting link in Jira comment
- Jira Issue: DEVOPS-303

[DEVOPS-303] Add ephemeral deployment environment details when posting link in Jira comment

---

.github/workflows/aks-deploy.yaml
.github/workflows/ephemeral-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-309" title="DEVOPS-309" target="_blank">DEVOPS-309</a></summary>
<br />
<table>
<tr>
<td>Resolve "docker buildx"-related errors in deploy workflows</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix `docker buildx` errors by switching to the docker/setup-buildx-action@v1 and docker/build-push-action@v2 GitHub actions to build and push the Docker images
- Jira Issue: DEVOPS-309
- Testing environment: [![Development AKS Deploy](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/aks-development.yml/bad …

[DEVOPS-309] Fix docker buildx errors

---

.github/workflows/aks-deploy.yaml
.github/workflows/ephemeral-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-309" title="DEVOPS-309" target="_blank">DEVOPS-309</a></summary>
<br />
<table>
<tr>
<td>Resolve "docker buildx"-related errors in deploy workflows</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fixing Docker build commands
- Jira Issue: DEVOPS-309

[DEVOPS-309] Fixing Docker build commands

---

.github/workflows/aks-deploy.yaml
.github/workflows/ephemeral-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/PUZSOC-6049" title="PUZSOC-6049" target="_blank">PUZSOC-6049</a></summary>
<br />
<table>
<tr>
<td>DevOps: Update key vault scripts to account for new Amazon Prime keys in TPS UI</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td><a href="https://amuniversal.atlassian.net/issues?jql=project%20%3D%20PUZSOC%20AND%20labels%20%3D%20ServiceDesk%20ORDER%20BY%20created%20DESC" title="ServiceDesk">ServiceDesk</a></td>
</tr>
</table>
</details>
---
- Combine get-envs steps after adding additional support for buildArgs
- Jira Issue: PUZSOC-6049

[PUZSOC-6049] Combine get-envs steps after adding additional support for buildArgs

---

.github/workflows/ephemeral-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-337" title="DEVOPS-337" target="_blank">DEVOPS-337</a></summary>
<br />
<table>
<tr>
<td>TPS UI ephemeral deployments breaking on PR descriptions with code formatting</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Switch to labels for ephemeral deployment triggers
- Jira Issue: DEVOPS-337

[DEVOPS-337] Switch to labels for ephemeral deployment triggers

---

.github/workflows/ephemeral-deploy.yaml

- Add checksum to URL to fix B2C redirect issues

[DEVOPS-XXX] Add checksum to URL to fix B2C redirect issues

---

.github/workflows/ephemeral-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-350" title="DEVOPS-350" target="_blank">DEVOPS-350</a></summary>
<br />
<table>
<tr>
<td>Don't run Next.js ephemeral deploy job if app already exists</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Skip updating Next.js variables if app has already been deployed
- Replace `BASE_URL` variables with the correct BASE_URL values rather than a modified version of the repository name.
- Jira Issue: DEVOPS-350
- [![📦️ Deploy Ephemeral Environment](https://github.com/Andrews-McMeel-Universal/puzzle-society_ui/actions/workflows/ephemeral-deployment …

[DEVOPS-350] Skip updating Next.js variables if app has already been deployed

---

.github/workflows/next-ci.yaml
.github/workflows/ui-ci.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-370" title="DEVOPS-370" target="_blank">DEVOPS-370</a></summary>
<br />
<table>
<tr>
<td>Update Next.js CI workflows with updated scripts in TPS UI</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Remove link checker and updated playwright install command
- Jira Issue: DEVOPS-370

[DEVOPS-370] Update Next.js CI yarn scripts

---

.github/workflows/ruby-ci.yaml

- Set INSTALL_NODE workflow input to string type
- Jira Issue: DEVOPS-XXX

[DEVOPS-XXX] Set INSTALL_NODE workflow input to string type

---

.github/workflows/ephemeral-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-373" title="DEVOPS-373" target="_blank">DEVOPS-373</a></summary>
<br />
<table>
<tr>
<td>Ephemeral Deployments scaling down to 0</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add step to update the minimum replicas to 1
- Jira Issue: DEVOPS-373

[DEVOPS-373] Fix minimum replicas being set to 0 on ephemeral deployments

---

.github/workflows/simple-lint.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-376" title="DEVOPS-376" target="_blank">DEVOPS-376</a></summary>
<br />
<table>
<tr>
<td>Prettier running without using configuration files in TPS UI</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Check for bool type instead of string
- Jira Issue: DEVOPS-376

[DEVOPS-376] Fix prettier not using configuration files

---

.github/workflows/ephemeral-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-378" title="DEVOPS-378" target="_blank">DEVOPS-378</a></summary>
<br />
<table>
<tr>
<td>Ephemeral deployment not deploying new commits properly</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add image tag that includes image checksum and use that for the deploy instead of just the Jira ticket.
- Jira Issue: DEVOPS-378
- Testing environment: [![📦️ Deploy Ephemeral Environment](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/ephemeral-deployments.yml/badge.svg?branch=bug%2FDEVOPS-378%2Ffix-ephemeral-depl …

[DEVOPS-378] Fix ephemeral deployments not deploying new commits

---

.github/workflows/aks-deploy.yaml
.github/workflows/azfunction-deploy.yaml
.github/workflows/b2c-build-and-deploy.yaml
.github/workflows/publish-nuget-package.yaml
.github/workflows/update-game-config.yaml
.github/workflows/wpe-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-384" title="DEVOPS-384" target="_blank">DEVOPS-384</a></summary>
<br />
<table>
<tr>
<td>Add option to manually trigger deploy workflows with an existing tag</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add `checkoutRef` inputs for deploying specific tags
- Jira Issue: DEVOPS-384
- Testing environment: [![🚀 Deploy](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/deploy.yml/badge.svg?branch=main)](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/deploy.yml)

[DEVOPS-384] Add `checkoutRef` inputs for deploying specific tags

---

.github/workflows/update-game-config.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-406" title="DEVOPS-406" target="_blank">DEVOPS-406</a></summary>
<br />
<table>
<tr>
<td>Game config deployment failing on package error</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix game config SimplySql PowerShell Module issues
- Move script to workflow
- Add steps in workflow to install modules
- Specify version `1.9.1` for the module
- Jira Issue: DEVOPS-406
- Successful workflow run: [![🚀 Deploy](https://github.com/Andrews-McMeel-Universal/game_config/actions/workflows/deploy.yml/badge.svg?branch=bug%2FDEVOPS-406%2Fgame-con …

[DEVOPS-406] Fix game config SimplySql PowerShell Module issues

---

.github/workflows/b2c-build-and-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-368" title="DEVOPS-368" target="_blank">DEVOPS-368</a></summary>
<br />
<table>
<tr>
<td>Rework B2C workflow inputs</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Remove broken/unused inputs in B2C workflow 
- Jira Issue: DEVOPS-368

[DEVOPS-368] Remove broken/unused inputs in B2C workflow

---

.github/workflows/aks-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-455" title="DEVOPS-455" target="_blank">DEVOPS-455</a></summary>
<br />
<table>
<tr>
<td>Cache frequently used Docker images with Azure Container Registry Artifact Caching</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Move login to ACR step before the build step
- Jira Issue: DEVOPS-455

[DEVOPS-455] Update workflow to use Azure Container Registry for pulling images

---

.github/workflows/aks-deploy.yaml

- Only disable delete access for image on AKS deploys
- Jira Issue: JIRA-XXX

[DEVOPS-XXX] Only disable delete access for image on AKS deploys

---

.github/workflows/aks-deploy.yaml

…yment was found
- Fix issue where workflow would fail if no previous deployment was found
- Jira Issue: JIRA-XXX

[DEVOPS-XXX] Fix issue where workflow would fail if no previous deployment was found

---

.github/workflows/azfunction-deploy.yaml
.github/workflows/clear-azure-redis-cache.yaml
.github/workflows/ephemeral-deploy.yaml
.github/workflows/purge-cdn.yaml
.github/workflows/update-azureapimanagement.yaml
.github/workflows/update-game-config.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-460" title="DEVOPS-460" target="_blank">DEVOPS-460</a></summary>
<br />
<table>
<tr>
<td>Azure Login step failing in deploy workflows</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Update azure/login action to v2
- Jira Issue: DEVOPS-460

[DEVOPS-460] Update azure/login action to v2

---

.github/workflows/update-azureapimanagement.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-462" title="DEVOPS-462" target="_blank">DEVOPS-462</a></summary>
<br />
<table>
<tr>
<td>Remove staging API access from Azure API Update GitHub Actions workflow</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Remove old staging API integration in Update API Management workflow
- Jira Issue: DEVOPS-462

[DEVOPS-462] Remove old staging API integration

---

.github/workflows/aks-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-463" title="DEVOPS-463" target="_blank">DEVOPS-463</a></summary>
<br />
<table>
<tr>
<td>Add environment name to Docker image tags to avoid variable mismatches</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add environment name to image tags
- Jira Issue: DEVOPS-463

[DEVOPS-463] Add environment name to image tags

---

.github/workflows/aks-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-467" title="DEVOPS-467" target="_blank">DEVOPS-467</a></summary>
<br />
<table>
<tr>
<td>AKS deploy workflows don't respect `maximumReplicas` config in `values.yaml` file</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix maxReplicas override from values.yaml
Result:
After setting the `maxReplicas` to `75` in the `values.yaml` file.
| Environment | Screenshot |
| --- | --- |
| Staging | ![image](https://github.com/Andrews-McMeel-Universal/reusable_workflows/assets/111298136/a019bcd4-4428-44bc-9417-356436739f49) |
| Development (Testing …

[DEVOPS-467] Fix maxReplicas override from values.yaml

---

.github/workflows/update-azureapimanagement.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/RECUR-186" title="RECUR-186" target="_blank">RECUR-186</a></summary>
<br />
<table>
<tr>
<td>[DEVOPS] Research how to deploy v1 and v2 APIs separately</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Update "update-azureapimanagement.yml" workflow to deploy individual API versions within the same version set.
- Updates the "Original" version so that the original endpoints continue working. Relies on the `API_SPECIFICATION_PATH` repository variable to determine the default/original API spec.
- Searches for a "Vx" directory for each version …

[RECUR-186] Deploy individual API versions

---

.github/workflows/update-azureapimanagement.yaml

- Revert loop for publishing API versions
- Jira Issue: RECUR-190

[RECUR-190] Revert loop for publishing API versions

---

.github/workflows/aks-deploy.yaml
.github/workflows/azfunction-deploy.yaml
.github/workflows/b2c-build-and-deploy.yaml
.github/workflows/update-game-config.yaml
.github/workflows/wpe-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-477" title="DEVOPS-477" target="_blank">DEVOPS-477</a></summary>
<br />
<table>
<tr>
<td>Send deployment alerts to Teams channel</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
<td>Resolved</td>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Send deployment notifications to Teams channel
Result:
- Jira Issue: DEVOPS-477

[DEVOPS-477] Send deployment notifications to Teams channel

---

.github/workflows/aks-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-485" title="DEVOPS-485" target="_blank">DEVOPS-485</a></summary>
<br />
<table>
<tr>
<td>Lower maxReplicas for Kubernetes deployments in staging and development</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Hard code maxReplicas for dev and staging
- Jira Issue: DEVOPS-485

[DEVOPS-485] Hard code maxReplicas for dev and staging

---

.github/workflows/update-azureapimanagement.yaml

- Fix issue where original version had no ApiVersionSetId set
- Jira Issue: JIRA-XXX

[RECUR-186] Fix issue where original version had no ApiVersionSetId set

---

.github/workflows/aks-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-495" title="DEVOPS-495" target="_blank">DEVOPS-495</a></summary>
<br />
<table>
<tr>
<td>Add Git submodule support in reusable GitHub Actions workflows</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add git submodule support in AKS deploy workflow
- Jira Issue: DEVOPS-495
- Testing environment: [![🚀 Deploy](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/deploy.yml/badge.svg?branch=story%2FDEVOPS-495%2Fadd-git-submodule-support)](https://github.com/Andrews-McMeel-Universal/reusable_workflows-te …

[DEVOPS-495] Add git submodule support in AKS deploy workflow

---

.github/workflows/docker-ci.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/UEXPRESS-1171" title="UEXPRESS-1171" target="_blank">UEXPRESS-1171</a></summary>
<br />
<table>
<tr>
<td>[DevOps] Add PR check to run docker build</td>
</tr>
<tr>
<th>Type</th>
<td>
Maintenance
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add get-envs to Docker CI workflow
- Jira Issue: UEXPRESS-1171
- Testing environment: [![✅ Application CI](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/ci.yml/badge.svg)](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/ci.yml)

[UEXPRESS-1171] Add get-envs to Docker CI workflow

---

.github/workflows/update-addns.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-530" title="DEVOPS-530" target="_blank">DEVOPS-530</a></summary>
<br />
<table>
<tr>
<td>Update Boley DNS workflow failing on "Record already exists"</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Replace Azure PowerShell actions and update logging
- Only update record if it needs to be changed
- Move timeout to update DNS step
- Convert `azure/powershell` actions to base pwsh shell scripts
- Jira Issue: DEVOPS-530

[DEVOPS-530] Replace Azure PowerShell actions and update logging

---

.github/workflows/azfunction-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-535" title="DEVOPS-535" target="_blank">DEVOPS-535</a></summary>
<br />
<table>
<tr>
<td>Recurly Notification Manager deployment failed</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Install jq requirement in Azure Function Deploy workflow
- Jira Issue: DEVOPS-535
- Testing environment: [![🚀 Deploy](https://github.com/Andrews-McMeel-Universal/recurly-notification-manager_function/actions/workflows/deploy.yml/badge.svg)](https://github.com/Andrews-McMeel-Universal/recurly-notification-manager_function/actions/workflows/deploy.yml)

[DEVOPS-535] Install jq requirement in Azure Function Deploy workflow

---

.github/workflows/aks-deploy.yaml

- Use new repository variable for AKS cluster resource group
- Jira Issue: DEVOPS-545

[DEVOPS-545] Use new repository variable for AKS cluster resource group

---

.github/workflows/clear-azure-redis-cache.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-552" title="DEVOPS-552" target="_blank">DEVOPS-552</a></summary>
<br />
<table>
<tr>
<td>Clear Redis Caches Workflow not clearing caches properly</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix Az.RedisCache PowerShell Package install in Clear Redis Cache workflow by adding the `-Force` argument to the command
https://github.com/Andrews-McMeel-Universal/gocomics_cms/actions/runs/11133095254/job/30938658481
- Jira Issue: DEVOPS-552

[DEVOPS-552] Fix Az.RedisCache PowerShell Package install in Clear Redis Cache workflow

---

.github/workflows/simple-lint.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-560" title="DEVOPS-560" target="_blank">DEVOPS-560</a></summary>
<br />
<table>
<tr>
<td>Prettier linter not committing changed files in GC UI</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix prettier linter not committing changes for changed files
- Jira Issue: DEVOPS-560

[DEVOPS-560] Fix prettier linter not committing changes for changed files

---

.github/workflows/mega-lint.yaml
.github/workflows/ruby-ci.yaml

- Update `actions/setup-node` to v4

[DEVOPS-XXX] Update `actions/setup-node` to v4

---

.github/workflows/simple-lint.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-600" title="DEVOPS-600" target="_blank">DEVOPS-600</a></summary>
<br />
<table>
<tr>
<td>GC: Prettier not respecting config in repository</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Install prettier version specified in `package.json`.
- Add step to install `jq` to use for parsing the version from the JSON output
- Replaced `creyD/prettier_action` action with AMU fork that uses Yarn as the package manager: [Andrews-McMeel-Universal/prettier_action](https://github.com/Andrews-McMeel-Universal/prettier_action)
- Remove …

[DEVOPS-600] Install prettier version specified in `package.json`

---

.github/workflows/simple-lint.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-607" title="DEVOPS-607" target="_blank">DEVOPS-607</a></summary>
<br />
<table>
<tr>
<td>Prettier Linter failing in non-Node projects</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix prettier version check
- Jira Issue: DEVOPS-607

[DEVOPS-607] Fix prettier version check

---

.github/workflows/azfunction-deploy.yaml
.github/workflows/clear-azure-redis-cache.yaml
.github/workflows/ruby-ci.yaml
.github/workflows/simple-lint.yaml

…dency
- Replace APT package install action with deprecated dependency
- Jira Issue: DEVOPS-612

[DEVOPS-612] Replace APT package install action with deprecated dependency

---

.github/workflows/azfunction-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-608" title="DEVOPS-608" target="_blank">DEVOPS-608</a></summary>
<br />
<table>
<tr>
<td>Azure Function App environment variables are not updating after re-deploy</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
@tflint-AMU noticed that GoComics MyFollows app environment variables were not updating after making changes to the key vault secrets and restarting the last deployment. 
Due to the environment variables not being pulled in during the build process (before the deploy step), the only reference to the environment variables are the links …

[DEVOPS-608] Restart Az Func app after deploy step

---

.github/workflows/update-major-release.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-613" title="DEVOPS-613" target="_blank">DEVOPS-613</a></summary>
<br />
<table>
<tr>
<td>Automatically update major version tag after publishing release</td>
</tr>
<tr>
<th>Type</th>
<td>
Improvement
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Automatically update major version tag on published release
- Jira Issue: DEVOPS-613

[DEVOPS-613] Automatically update major version tag on published release

---

.github/workflows/purge-azure-frontdoor-caches.yaml
.github/workflows/purge-cdn.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-616" title="DEVOPS-616" target="_blank">DEVOPS-616</a></summary>
<br />
<table>
<tr>
<td>Purge CDN Job Failing for Game Deployments</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add Azure FrontDoor Purge Cache workflow
- Remove TPS game conditions from `purge-cdn.yml` workflow and simplify input checks
- Jira Issue: DEVOPS-616

[DEVOPS-616] Add Azure FrontDoor Purge Cache workflow

---

.github/workflows/aks-deploy.yaml
.github/workflows/b2c-build-and-deploy.yaml
.github/workflows/clear-azure-redis-cache.yaml
.github/workflows/purge-cdn.yaml
.github/workflows/update-addns.yaml
.github/workflows/update-azureapimanagement.yaml
.github/workflows/update-game-config.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-620" title="DEVOPS-620" target="_blank">DEVOPS-620</a></summary>
<br />
<table>
<tr>
<td>Optimize inputs and steps in reusable workflows</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
Optimize reusable workflows
- Cache install of PowerShell modules
- Get rid of GitHub action for updating “DeployedApplications” table in Azure
- Automatically resolve resource group for AKS clusters
- Remove redundant/unused inputs and configs
- Convert azure/powershell@vx actions to simple PowerShell scripts
- Jira Issue: DEVOPS-620
- Reusable Workflows …

[DEVOPS-620] Optimize inputs and steps in reusable workflows

---

.github/workflows/aks-deploy.yaml
.github/workflows/update-addns.yaml
.github/workflows/update-azureapimanagement.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-618" title="DEVOPS-618" target="_blank">DEVOPS-618</a></summary>
<br />
<table>
<tr>
<td>Redesign Helm implementation for scalability</td>
</tr>
<tr>
<th>Type</th>
<td>
Improvement
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
Re-design Helm implementation for scalability
- Added new `serviceIngressWhitelist` input to make it easier to update Ingress whitelist annotations for BE services
- Added repository variable support for setting the admin ingress whitelist
- Simplified structure of "Extract Helm Values" step
- Removed "Get-Envs" function
- Moved related commands and …

[DEVOPS-618] Re-design Helm implementation for scalability

---

.github/workflows/azfunction-deploy.yaml
.github/workflows/bump-nuget-version.yaml
.github/workflows/bump-versions.yaml
.github/workflows/clear-azure-redis-cache.yaml
.github/workflows/dependabot-automations.yaml
.github/workflows/dotnet-ci.yaml
.github/workflows/jira-lint.yaml
.github/workflows/publish-nuget-package.yaml
.github/workflows/simple-lint.yaml

- Move repo var defaults from workflow calls to workflow inputs
- Jira Issue: DEVOPS-XXX

[DEVOPS-XXX] Move repo var defaults from workflow calls to workflow inputs

---

.github/workflows/aks-deploy.yaml

Add QOL updates to values override step after testing
- Set `$environment` variable before the `./deployments/<environment>-charts` checks and variable setting
- Automatically set the `cert-manager.io/cluster-issuer` annotation for all ingresses to `letsencrypt-prod`  so that we can easily change it in the future and so that it's not set in each individual repository.
- Set environment in the `values-override.yaml` file to use when evaluating conditions in the Helm templates (specifically, checking to see if the environment is set to `production` and only then, adding the `wwwredirect` ingress).
- Remove the www redirect ingress if environment is not set to "production" to avoid modifying the redundant ingress.
- Removed verbose debugging message related to adding the `ingressClassName` …

[DEVOPS-XXX] Add QOL updates to values override step after testing

---

.github/workflows/aks-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-623" title="DEVOPS-623" target="_blank">DEVOPS-623</a></summary>
<br />
<table>
<tr>
<td>Updated Helm templates are leading to errors during deployments</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
Fix values override syntax errors seen in this workflow run: https://github.com/Andrews-McMeel-Universal/7-little-words_game/actions/runs/13080903870
- Add hyphen before ingress name to fix the ingress values not being a usable array when baking the helm templates
- Order ingress keys to fix issue with the name appearing below other keys, …

[DEVOPS-623] Fix values override syntax errors

---

.github/workflows/simple-lint.yaml

- Retrieve only `prettier` package
- Jira Issue: DEVOPS-627

[DEVOPS-627] Retrieve only `prettier` package

---

.github/workflows/purge-cdn.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-630" title="DEVOPS-630" target="_blank">DEVOPS-630</a></summary>
<br />
<table>
<tr>
<td>B2C Asset Caches are not getting flushed after deploys</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add repo variable for CDN_RESOURCE_TYPE
- Jira Issue: DEVOPS-630

[DEVOPS-630] Add repo variable for CDN_RESOURCE_TYPE

---

.github/workflows/update-addns.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-632" title="DEVOPS-632" target="_blank">DEVOPS-632</a></summary>
<br />
<table>
<tr>
<td>Update AD DNS workflow not updating DNS records</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Replace DNS records if they already exist
- Add more debugging / error handling logic
- Incorporate try/catch statements throughout the script
- Jira Issue: DEVOPS-632
- Testing environment: [![🚀 Deploy](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/deploy.yml/badge.svg)](https://github.com/Andrews-McMeel-Universal/reusa …

[DEVOPS-632] Replace DNS records if they already exist

---

.github/workflows/aks-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-648" title="DEVOPS-648" target="_blank">DEVOPS-648</a></summary>
<br />
<table>
<tr>
<td>Set up Sentry action in GoComics 6 deploy workflows</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add sentry release action to deploy workflow
- Jira Issue: DEVOPS-648

[DEVOPS-648] Add sentry release action to deploy workflow

---

.github/workflows/aks-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-657" title="DEVOPS-657" target="_blank">DEVOPS-657</a></summary>
<br />
<table>
<tr>
<td>Move K8s service annotation defaults to AKS deploy workflow</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Set service annotation defaults if they're not set in the `values.yaml` file
- Jira Issue: DEVOPS-657

[DEVOPS-657] Set service annotation defaults

---

.github/workflows/release-drafter.yml

We've been having issues with the latest release of the release drafter where it has been duplicating draft releases. This PR is to update the release drafter workflow in this repository to convert it into a reusable workflow so that we can link to it in other repositories and fix the version.

[DEVOPS-XXX] Convert release drafter workflow to be reusable

---

.github/workflows/aks-deploy.yaml
.github/workflows/clear-azure-redis-cache.yaml
.github/workflows/update-addns.yaml
.github/workflows/update-azureapimanagement.yaml
.github/workflows/update-game-config.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-662" title="DEVOPS-662" target="_blank">DEVOPS-662</a></summary>
<br />
<table>
<tr>
<td>Deploys failing due to missing PowerShell modules directory</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
Fix missing PowerShell modules directory errors
- Fix: Switch back to Install-Module cmdlets. Caching the modules is more pain than what it's worth and it would be better to not rely on an external dependency anyways
- Jira Issue: DEVOPS-662

[DEVOPS-662] Fix missing PowerShell modules directory errors

---

.github/workflows/template-sync.yml

- Update sync workflow to be a reusable workflow
- Jira Issue: DEVOPS-664

[DEVOPS-664] Update sync workflow to be a reusable workflow

---

.github/workflows/aks-deploy.yaml

This PR updates the AKS deploy workflow to retrieve DNS hostnames from the ingress configurations defined in the values override step. This is part of a larger effort to make the Helm templates more templatized and to fix issues where only some ingress hostnames were being updated and also to account for other domains related to the app that are specified in the ingress definitions (for ex. `kcur.puzzlesociety.com`)
Previously, the "Extract Helm Values" step provided the DNS subdomain, which meant only the main ingress hostname was being updated. This approach risked divergence from the actual hostnames used. Now, we directly pull the hostnames from the values override step, which brings several benefits:
- We can iterate through each ingress hostname and create DNS records accordingly.
- …

[DEVOPS-XXX] Retrieve DNS hostnames to update from ingresses in values override step

---

.github/workflows/publish-ruby-gems.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-683" title="DEVOPS-683" target="_blank">DEVOPS-683</a></summary>
<br />
<table>
<tr>
<td>Create workflow to publish gems directly to gems.amuniversal.com</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add Publish Ruby Gems workflow
- Jira Issue: DEVOPS-682
- Testing environment: [![🚀 Deploy](https://github.com/Andrews-McMeel-Universal/admin-assets_gem/actions/workflows/deploy.yml/badge.svg)](https://github.com/Andrews-McMeel-Universal/gem-in-a-box/actions/runs/14738393673/job/41370243529)

[DEVOPS-682] Add Publish Ruby Gems workflow

---

.github/workflows/ephemeral-deploy.yaml
.github/workflows/jira-lint.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-694" title="DEVOPS-694" target="_blank">DEVOPS-694</a></summary>
<br />
<table>
<tr>
<td>Ephemeral Deployment Workflow Not Parsing Jira Issue Key from PR Details</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Sanitize ephemeral deployment Jira issue key parsing
- Jira Issue: DEVOPS-694

[DEVOPS-694] Sanitize ephemeral deployment Jira issue key parsing

---

.github/workflows/ephemeral-deploy.yaml

- Automatically transition ephemeral deployment Jira tickets to "In QA (Ephemeral)" after an ephemeral deploy finishes
Test:

[DEVOPS-XXX] Automatically transition ephemeral deployment Jira tickets

---

.github/workflows/aks-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-699" title="DEVOPS-699" target="_blank">DEVOPS-699</a></summary>
<br />
<table>
<tr>
<td>AKS Deploy ingress not being set if the whitelist is a comma separated list</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add support for comma separated ingress whitelist value
- Jira Issue: DEVOPS-699
- Testing environment: [![🚀 Deploy](https://github.com/Andrews-McMeel-Universal/sudoku_game/actions/workflows/deploy.yml/badge.svg)](https://github.com/Andrews-McMeel-Universal/sudoku_game/actions/runs/15564030306)

[DEVOPS-699] Add support for comma separated ingress whitelist value

---

.github/workflows/aks-deploy.yaml

- Fix update DNS step failing by sanitizing the INGRESSES list before passing it into the update DNS commands
- Jira Issue: DEVOPS-711

[DEVOPS-711] Fix update DNS step failing

---

.github/workflows/aks-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-725" title="DEVOPS-725" target="_blank">DEVOPS-725</a></summary>
<br />
<table>
<tr>
<td>GoComics UI minReplicas set to 20 in staging</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Set override for minReplicas
- Jira Issue: DEVOPS-725

[DEVOPS-725] Set override for minReplicas in deploy workflow

---

.github/workflows/aks-deploy.yaml

- Fix "secret already exists" errors during AKS deploys
- Jira Issue: DEVOPS-726

[DEVOPS-726] Fix "secret already exists" errors during AKS deploys

---

.github/workflows/aks-deploy.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-731" title="DEVOPS-731" target="_blank">DEVOPS-731</a></summary>
<br />
<table>
<tr>
<td>403 error on Staging GC API Info page </td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
…ot nil
- Set privateIngress whitelist to admin whitelist if its not nil
- Jira Issue: DEVOPS-731

[DEVOPS-731] Set privateIngress whitelist to admin whitelist if its not nil

---

.github/workflows/next-ci.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-733" title="DEVOPS-733" target="_blank">DEVOPS-733</a></summary>
<br />
<table>
<tr>
<td>Research: Utilize Microsoft Playwright Testing for speeding up integration tests</td>
</tr>
<tr>
<th>Type</th>
<td>
Research
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Speed up Playwright tests
- Jira Issue: DEVOPS-733

[DEVOPS-733] Speed up Playwright tests

---

.github/workflows/next-ci.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-733" title="DEVOPS-733" target="_blank">DEVOPS-733</a></summary>
<br />
<table>
<tr>
<td>Research: Improve Playwright tests run time</td>
</tr>
<tr>
<th>Type</th>
<td>
Research
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Improve Next.js CI test runtimes
Tests:
- <img width="927" height="436" alt="image" src="https://github.com/user-attachments/assets/5b5b9359-f676-474a-905b-73581b0fe377" />
- <img width="891" height="475" alt="image" src="https://github.com/user-attachments/assets/043572c1-3a19-4c55-85ac-4f1bde4c9266" />
- Jira Issue: DEVOPS-733

[DEVOPS-733] Improve Next.js CI test runtimes

---

.github/workflows/aks-deploy.yaml
.github/workflows/docker-ci.yaml
.github/workflows/next-ci.yaml

<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-733" title="DEVOPS-733" target="_blank">DEVOPS-733</a></summary>
<br />
<table>
<tr>
<td>Research: Improve Playwright tests run time</td>
</tr>
<tr>
<th>Type</th>
<td>
Research
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Enable caching for the env-vars GitHub action
- Jira Issue: DEVOPS-733

[DEVOPS-733] Enable caching for the env-vars GitHub action
