- .github/workflows/aks-deploy.yaml
The 2.1.13.1 release was made to revert the changes made to set the variable in PowerShell entirely and to move it back the inline bash script. This PR is to move it back to the PowerShell setenvs step and fix the errors it was creating due to too short of an appName value.
Here's a GitHub action that was breaking due to this bug: https://github.com/Andrews-McMeel-Universal/uexpress_ui/actions/runs/4048471886/jobs/6963921472
- Fixing the release var setting in the "Checkout Code and Variables for the environment" step.
> [DEVOPS] fix release var in setenvs step

- .github/workflows/aks-deploy.yaml
Fixing a bug where, if quotes are included in the string object of the workflow inputs, any comparisons using those inputs can break.
Test workflow: [![AKS Deployment](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/aks-deployment.yml/badge.svg?branch=aks-deploy-2.1.16)](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/aks-deployment.yml)
> [DEVOPS] Fix quoting issue with workflow_call inputs

- .github/workflows/next-ci.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-210" title="DEVOPS-210" target="_blank">DEVOPS-210</a></summary>
<br />
<table>
<tr>
<td>DevOps: Create composite actions for UI build and install steps</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td><a href="https://amuniversal.atlassian.net/issues?jql=project%20%3D%20DEVOPS%20AND%20labels%20%3D%20ServiceDesk%20ORDER%20BY%20created%20DESC" title="ServiceDesk">ServiceDesk</a></td>
</tr>
</table>
</details>
---
- Switch to new `cache-next-build` and `cache-next-install` composite actions in `next-ci.yaml` workflow
- Jira Issue: DEVOPS-210
> [DEVOPS-210] switch to next install/build composite actions

- .github/workflows/b2c-build-and-deploy.yaml
- README.md
- Removed redundant workflow inputs
> [DEVOPS-XXX] Resolve B2C deploy issues

- .github/workflows/clear-azure-redis-cache.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-242" title="DEVOPS-242" target="_blank">DEVOPS-242</a></summary>
<br />
<table>
<tr>
<td>DevOps: Create GitHub Actions workflow for clearing Azure Redis Caches</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td><a href="https://amuniversal.atlassian.net/issues?jql=project%20%3D%20DEVOPS%20AND%20labels%20%3D%20ServiceDesk%20ORDER%20BY%20created%20DESC" title="ServiceDesk">ServiceDesk</a></td>
</tr>
</table>
</details>
---
- Added workflow to clear Redis caches based off environment
- Jira Issue: DEVOPS-242
- Testing Environment: [![Clear Azure Redis …
> [DEVOPS-242] add clear redis caches workflow

- .github/release.yml
- .github/workflows/template-sync.yml
- .gitignore
- .prettierignore
Merge Andrews-McMeel-Universal/.github c1290c5
> 🔄 Sync with @Andrews-McMeel-Universal/.github

- .github/workflows/aks-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-236" title="DEVOPS-236" target="_blank">DEVOPS-236</a></summary>
<br />
<table>
<tr>
<td>Switch to using semantic versioning on Azure Container Registry image tags</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Modified AKS deploy to automatically tag images as "latest" and for staging and production deploys, the major release version like so: 
- Jira Issue: DEVOPS-236
- Testing environment: [![Staging AKS Deploy](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/aks-staging.yml/badge.svg)](https://github …
> [DEVOPS-236] Use release in Docker image registry image tag

- .github/workflows/b2c-build-and-deploy.yaml
- Switch to new Docker-based deploy-trustframework-policy action after abandoning the old/deprecated-ish action that does not return error messages when failing.
> [DEVOPS-XXX] Switch to new Docker-based B2C deploy-trustframework-policy action

- .github/workflows/b2c-build-and-deploy.yaml
- Use new v6 version of deploy B2C policy action
- Use `${{ env.[VAR] }}` variable references
- Remove deprecated `azureB2CProductId` input
- Testing environment: [![Development B2C Deployment](https://github.com/Andrews-McMeel-Universal/gocomics_b2c/actions/workflows/deploy-development.yml/badge.svg?branch=devops%2FDEVOPS-XXX%2Fconvert-to-composite-action)](https://github.com/Andrews-McMeel-Universal/gocomics_b2c/actions/workflows/deploy-development.yml)
> [DEVOPS-XXX] Use new v6 version of deploy B2C policy action

- .github/workflows/dotnet-ci.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-253" title="DEVOPS-253" target="_blank">DEVOPS-253</a></summary>
<br />
<table>
<tr>
<td>Resolve GoComics Store .NET Application CI dependency failures</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- [Added `obj` directories to install-cache step in dotnet-ci.yaml](https://github.com/Andrews-McMeel-Universal/reusable_workflows/commit/ae8c071f807958c3814cb276e95343e22d3b7deb)
- Jira Issue: DEVOPS-253
> [DEVOPS-253] Resolve .NET Application CI dependency caching issues

- .github/workflows/bump-versions.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-265" title="DEVOPS-265" target="_blank">DEVOPS-265</a></summary>
<br />
<table>
<tr>
<td>Update Bump versions workflow to account for environment-based Helm charts</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Adding `environmentCharts` input to bump versions workflow to account for repositories that have environment-based Helm charts
- Test environment: [![Bump Version](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/bump-versions.yml/badge.svg)](https://github.com/Andrews-McMeel-Universal/reusable_wo …
> [DEVOPS-265] Add environmentCharts input

- .github/workflows/aks-deploy.yaml
- .github/workflows/azfunction-deploy.yaml
- .github/workflows/b2c-build-and-deploy.yaml
- .github/workflows/clear-azure-redis-cache.yaml
- .github/workflows/next-ci.yaml
- .github/workflows/purge-cdn.yaml
- .github/workflows/ruby-ci.yaml
- .github/workflows/ui-ci.yaml
- .github/workflows/update-azureapimanagement.yaml
- .github/workflows/update-game-config.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-272" title="DEVOPS-272" target="_blank">DEVOPS-272</a></summary>
<br />
<table>
<tr>
<td>Switch back to the default Azure Login GitHub action in the reusable workflows</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Switch back to default azure login action where applicable. In other cases, just remove it if `get-envs` action is run since it already logs in to Azure.
- Jira Issue: DEVOPS-272
> [DEVOPS-272] Switch back to default Azure login action to avoid caching issues

- .github/workflows/simple-lint.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-280" title="DEVOPS-280" target="_blank">DEVOPS-280</a></summary>
<br />
<table>
<tr>
<td>Resolve failed prettier dependabot PR checks in TPS UI</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add `runYarnInstall` input to Simple Lint workflow that runs `yarn install` before running prettier
- Jira Issue: DEVOPS-280
> [DEVOPS-280] Add runYarnInstall input to Simple Lint workflow

- .github/workflows/ephemeral-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-263" title="DEVOPS-263" target="_blank">DEVOPS-263</a></summary>
<br />
<table>
<tr>
<td>Create workflow for deploying Azure Container Instances for ephemeral deployments</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add steps to rebuild Next.js apps with updated variables to fix B2C authentication issues.
- Jira Issue: DEVOPS-263
- Testing environment: [![Ephemeral Deployments](https://github.com/Andrews-McMeel-Universal/puzzle-society_ui/actions/workflows/ephemeral-deployment.yml/badge.svg?branch=research%2FPUZSOC-5782%2Fephemeral-depl …
> [DEVOPS-263] Add steps to rebuild Next.js apps with updated variables

- .github/workflows/dependabot-automations.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-279" title="DEVOPS-279" target="_blank">DEVOPS-279</a></summary>
<br />
<table>
<tr>
<td>Rework Dependabot Automations Reusable Workflow to add more auto-merge/auto-approve options</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Changed `autoApprove` and `autoMerge` inputs in dependabot automations workflow to be array objects that allow the user to choose which type of updates they would like to auto-approve and auto-merge.
- Jira Issue: DEVOPS-279
- Testing environment: Dependabot created the PR listed below with the `autoApprove` and …
> [DEVOPS-279] Changed autoApprove and autoMerge inputs to arrays

- .github/workflows/jira-lint.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-269" title="DEVOPS-269" target="_blank">DEVOPS-269</a></summary>
<br />
<table>
<tr>
<td>Research alternatives or fixes for Jira linter GitHub action</td>
</tr>
<tr>
<th>Type</th>
<td>
Improvement
</td>
</tr>
<tr>
<td>New</td>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Check if Jira Linter has already posted a missing Jira issue key comment before running
- Jira Issue: DEVOPS-269
- Testing environment: 
- [Jira Linter Workflow Run](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/runs/6579557572/job/17875700269)
- [Pull Request](https://github.com/Andrews-McMeel-Universal/reusable_work …
> [DEVOPS-269] Check if Jira Linter has already posted a missing Jira issue key comment before running

- .github/workflows/jira-lint.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-269" title="DEVOPS-269" target="_blank">DEVOPS-269</a></summary>
<br />
<table>
<tr>
<td>Research alternatives or fixes for Jira linter GitHub action</td>
</tr>
<tr>
<th>Type</th>
<td>
Improvement
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Lint PR for Jira issue key before Jira linter runs
- Jira Issue: DEVOPS-269
> [DEVOPS-269] Lint PR for Jira issue key before Jira linter

- .github/workflows/aks-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-284" title="DEVOPS-284" target="_blank">DEVOPS-284</a></summary>
<br />
<table>
<tr>
<td>Update AKS deploy workflow to account for new AKS clusters</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add support for deploying to default Kubernetes namespace by adding the `environmentNamespace` input.
- Jira Issue: DEVOPS-284
- Testing environment: [![Reusable Workflow Test](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/aks-development.yml/badge.svg?branch=story%2FDEVOPS-284%2Fadd-environment-clust …
> [DEVOPS-284] Add support for deploying to default Kubernetes namespace

- .github/workflows/b2c-build-and-deploy.yaml
- .github/workflows/b2c-ci.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/PUZSOC-5920" title="PUZSOC-5920" target="_blank">PUZSOC-5920</a></summary>
<br />
<table>
<tr>
<td>DevOps: B2C Workflows not generating auth assets</td>
</tr>
<tr>
<th>Type</th>
<td>
Maintenance
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Use `yarn build` instead of `yarn generate` in B2C CI and deploy workflows after B2C template updates
- Jira Issue: [PUZSOC-5920](https://amuniversal.atlassian.net/browse/PUZSOC-5920)
[PUZSOC-5920]: https://amuniversal.atlassian.net/browse/PUZSOC-5920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PUZSOC-5920] Use yarn build in B2C policies

- .github/workflows/aks-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-294" title="DEVOPS-294" target="_blank">DEVOPS-294</a></summary>
<br />
<table>
<tr>
<td>Scale down Nginx Ingress Controller logging in the AKS cluster</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Added `enableNginxIngressLogging` input to AKS deploy workflow to cut down on excessive Nginx controller logging in Kubernetes. Default is set to "false". In projects that we'll want access logging, we'll set the input to "true" in the deploy workflow inputs
- Jira Issue: DEVOPS-294
> [DEVOPS-294] Add enableNginxIngressLogging input to AKS deploy workflow

- .github/workflows/ephemeral-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-301" title="DEVOPS-301" target="_blank">DEVOPS-301</a></summary>
<br />
<table>
<tr>
<td>Post ephemeral deployment link to Jira ticket when ephemeral deployment is ready</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- If deployment hasn't already been linked to the ticket, link the ephemeral deployment URL in Jira ticket after successful deployment.
- Jira Issue: DEVOPS-301
- Ephemeral deployment link: 
- Testing environment: [![📦️ Deploy Ephemeral Environment](https://github.com/Andrews-McMeel-Universal/puzzle-society_ui/actions/workflows …
> [DEVOPS-301] Link ephemeral deployment URL in Jira ticket after successful deployment

- .github/workflows/dotnet-ci.yaml
- Added `projectName` input to Dotnet CI workflow that sets the `working-directory` for the `dotnet restore`, `dotnet build`, `dotnet test` commands if set.
> [DEVOPS-XXX] Add option to set working-directory in Dotnet CI workflow

- .github/workflows/bump-nuget-version.yaml
- .github/workflows/publish-nuget-package.yaml
- Added `libraryName` input to Bump Nuget Package Version workflow to add support for multiple libraries contained within a single project.
- Applied prettier changes to Increment Version script
- Made `projectName` input mandatory since accounting for the exact library/project name does not scale well.
- Added a separate commit step if the `libraryName` input is passed into the workflow so that the commit messages have the `libraryName` included in them.
- Added `libraries` input to workflow to add support for multiple libraries contained within a single project.
> [DEVOPS-XXX] Add support multiple Nuget project libraries in Publish Nuget Package workflow

- .github/workflows/aks-deploy.yaml
- .github/workflows/ephemeral-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-309" title="DEVOPS-309" target="_blank">DEVOPS-309</a></summary>
<br />
<table>
<tr>
<td>Switch to docker buildx commands in reusable workflows</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Update `docker build` commands to `docker buildx build` to account for the new `buildx` command being the default in the latest Ubuntu images.
- Jira Issue: DEVOPS-309
- Example failed build: https://github.com/Andrews-McMeel-Universal/puzzle-society_ui/actions/runs/6866150321/job/18671869277
> [DEVOPS-309] Switch to Docker buildx commands to fix failing builds

- .github/workflows/aks-deploy.yaml
- .github/workflows/ephemeral-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-306" title="DEVOPS-306" target="_blank">DEVOPS-306</a></summary>
<br />
<table>
<tr>
<td>Add build arg compatibility to get-envs custom GitHub action</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Switched to using `setBuildArguments` input with the get-envs action in the "Generate build args from Azure Key Vaults" step in the AKS deploy workflow
- Switched to using `setBuildArguments` input with the get-envs action in the "Generate build args from Azure Key Vaults" step in the Ephemeral Deployments workflow
- Jira Issue: …
> [DEVOPS-306] Use new `setBuildArguments` input in get-envs action

- .github/workflows/ui-ci.yaml
- Moved playwright browsers install command to after the `yarn build` comand to fix App CI checks
- Jira Issue: DEVOPS-312
> [DEVOPS-312] Moved playwright browsers install command to fix App CI checks

- .github/workflows/ephemeral-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-332" title="DEVOPS-332" target="_blank">DEVOPS-332</a></summary>
<br />
<table>
<tr>
<td>Fix how the ephemeral deployments workflow searches for the environment from the PR description</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Ignore backticks in pull request descriptions in ephemeral deployments workflow
- Jira Issue: DEVOPS-332
> [DEVOPS-332] Ignore backticks in pull request descriptions in ephemeral deployments workflow

- .github/workflows/simple-lint.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-324" title="DEVOPS-324" target="_blank">DEVOPS-324</a></summary>
<br />
<table>
<tr>
<td>Prettier in simple lint workflow not respecting prettier config files</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Use repository config files when running prettier
- Jira Issue: DEVOPS-324
> [DEVOPS-324] Use repository config files when running prettier

- .github/workflows/aks-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-338" title="DEVOPS-338" target="_blank">DEVOPS-338</a></summary>
<br />
<table>
<tr>
<td>Add update-dns step back into AKS deploy workflow</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Combined `deploy` and `update-records` jobs to have both the AKS deploy step and the DNS step use the same `AKS_CLUSTER_NAME` input
- Removed redundant outputs from `GITHUB_STEP_SUMMARY`
- Jira Issue: DEVOPS-338
- Testing environment: [![Development AKS Deploy](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/aks-development. …
> [DEVOPS-338] Fix issue with update DNS step using old AKS cluster name

- .github/workflows/ephemeral-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-339" title="DEVOPS-339" target="_blank">DEVOPS-339</a></summary>
<br />
<table>
<tr>
<td>Ephemeral deployment workflow not deleting deployment or B2C redirect URIs after PR closes</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix if conditions in ephemeral deployment workflow
- Moved if condition from the `prepare` job to the `deploy` job.
- Fixed workflow triggers on a PR's 'synchronize', 'reopened', and 'opened' events by checking for all iterations of the `preview:` label.
- Jira Issue: DEVOPS-339
- Testing environment: [![📦️ Deploy …
> [DEVOPS-339] Fix if conditions in ephemeral deployment workflow

- .github/workflows/ephemeral-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-343" title="DEVOPS-343" target="_blank">DEVOPS-343</a></summary>
<br />
<table>
<tr>
<td>Extend URL checksum to max character limit in ephemeral deploy workflow</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Extend container app name to 32 characters to make the B2C redirect URIs more unique for Next.js ephemeral deployments.
- Jira Issue: DEVOPS-343
- Testing environment: [![📦️ Deploy Ephemeral Environment](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/ephemeral-deployments.yml/badge.svg?branch=sto …
> [DEVOPS-343] Extend container app name to 32 characters

- .github/workflows/ephemeral-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-349" title="DEVOPS-349" target="_blank">DEVOPS-349</a></summary>
<br />
<table>
<tr>
<td>Remove Jira ticket ID from ephemeral deployment app names</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Move Jira ticket ID to the end of app name in ephemeral deployments workflow
- Jira Issue: DEVOPS-349
- Testing environment: [![📦️ Deploy Ephemeral Environment](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/ephemeral-deployments.yml/badge.svg?branch=story%2FDEVOPS-349%2Fremove-jira-ticket-id-from-eph-deploy-names)] …
> [DEVOPS-349] Move Jira ticket ID to the end of app name in ephemeral deployments workflow

- .github/workflows/ephemeral-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-360" title="DEVOPS-360" target="_blank">DEVOPS-360</a></summary>
<br />
<table>
<tr>
<td>Next.js variables no longer being updated in ephemeral deployments</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix Next.js environmentVariables not being updated in ephemeral deployments by including `environmentVariables` from the `get-envs` and `next-vars` step in the right order
- Moved `remove-prime-keys` steps to be right after the `get-envs` step to reduce the amount of `environmentVariables` and `buildArguments` references throughout the …
> [DEVOPS-360] Fix Next.js environmentVariables not being updated in ephemeral deployments

- .github/workflows/simple-lint.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-376" title="DEVOPS-376" target="_blank">DEVOPS-376</a></summary>
<br />
<table>
<tr>
<td>Prettier not respecting config files in TPS UI</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Run [Andrews-McMeel-Universal/cache-yarn-install](https://github.com/Andrews-McMeel-Universal/cache-yarn-install) action instead of `yarn add` or `yarn install`
- Pass in `--plugin [PLUGIN]` arguments based off plugins referenced in `inputs.prettierPlugins` to prettier action
- Jira Issue: DEVOPS-376
- Testing environment: [![✅ …
> [DEVOPS-376] Fix prettier not respecting configuration files

- .github/workflows/do-not-merge.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-383" title="DEVOPS-383" target="_blank">DEVOPS-383</a></summary>
<br />
<table>
<tr>
<td>Fix "do not merge" label integration with GitHub PRs</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add do not merge workflow
- Jira Issue: DEVOPS-383
> [DEVOPS-383] Add do not merge workflow

- .github/workflows/jira-lint.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-405" title="DEVOPS-405" target="_blank">DEVOPS-405</a></summary>
<br />
<table>
<tr>
<td>Add functionality for skipping Jira linter checks if a specific label is added to a PR</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add option to disable the Jira linter workflow with the new 'disable-jira-linter' label to hide linting failures
PR labels:
Checks in testing environment:
- Jira Issue: DEVOPS-405
> [DEVOPS-405] Disable Jira linter with 'disable-jira-linter' label

- .github/workflows/aks-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-453" title="DEVOPS-453" target="_blank">DEVOPS-453</a></summary>
<br />
<table>
<tr>
<td>Restarting Docker builds in staging leads to pods starting with production image</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix image refs to use GitHub SHAs by default rather than tag names
- Jira Issue: DEVOPS-453
> [DEVOPS-453] Fix image refs to use GitHub SHAs

- .github/workflows/aks-deploy.yaml
- Restructure unlocking/untagging steps to not use the environment tags when unlocking/untagging the image.
- Rename "current image" steps/variables to "previous image"
- Jira Issue: DEVOPS-457
- Testing environment: [![🚀 Deploy](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/deploy.yml/badge.svg?branch=story%2FDEVOPS-457%2Faccount-for-missing-environment-tags)](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/deploy.yml)
> [DEVOPS-457] Restructure unlocking/untagging steps

- .github/workflows/bump-versions.yaml
- Add version input to bump versions workflow to add in the option for a specific version rather than relying solely on bumping the version to the next major/minor/patch release.
- Jira Issue: DEVOPS-464
- Working test: 
---
> [DEVOPS-464] Add version input to bump versions workflow

- .github/workflows/aks-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-480" title="DEVOPS-480" target="_blank">DEVOPS-480</a></summary>
<br />
<table>
<tr>
<td>Kubernetes pull secrets not appearing in K9s</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix pull secrets not showing up in K9s by adding an input to the K8s create secret action to set the namespace during when creating the secret.
- Jira Issue: DEVOPS-480
> [DEVOPS-480] Specify namespace when creating pull secret

- .github/actionlint.yaml
- .github/workflows/aks-deploy.yaml
- .github/workflows/update-azureapimanagement.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/RECUR-186" title="RECUR-186" target="_blank">RECUR-186</a></summary>
<br />
<table>
<tr>
<td>[DEVOPS] Research how to deploy v1 and v2 APIs separately</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Set `ingressWhitelist` input in AKS deploy workflow to the `KUBERNETES_INGRESS_WHITELIST` repository variable and have it default to the value in the `values.yaml` and otherwise, default to `0.0.0.0/0`
- Have the API management update workflow run on self-hosted GitHub Runner in the `amuaksdev101` cluster so that we can have a cloud VM/container pull …
> [RECUR-186] Deploy versioned API specs

- .github/workflows/update-azureapimanagement.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-490" title="DEVOPS-490" target="_blank">DEVOPS-490</a></summary>
<br />
<table>
<tr>
<td>Fix error codes with missing API versions in API deploy workflow</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix error code variables in API update workflow
Before:
```
API version V1 (https://development.subscription-service.amuniversal.com/swagger/v1/swagger.json): {
"openapi": "3.0.1",
"info": {
"title": "Subscription Service API",
"description": "<b>Environment:</b> Development (Release Build)\n\n<b>Environment Variable Source:</b> …
```
> [DEVOPS-490] Fix error code variables in API update workflow

- .github/workflows/docker-ci.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/UEXPRESS-1171" title="UEXPRESS-1171" target="_blank">UEXPRESS-1171</a></summary>
<br />
<table>
<tr>
<td>[DevOps] Add PR check to run docker build</td>
</tr>
<tr>
<th>Type</th>
<td>
Maintenance
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add input to customize health check path in Docker CI workflow
- Jira Issue: UEXPRESS-1171
> [UEXPRESS-1171] Add input to customize health check path in Docker CI workflow

- .github/workflows/azfunction-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-513" title="DEVOPS-513" target="_blank">DEVOPS-513</a></summary>
<br />
<table>
<tr>
<td>Azure Function deploy workflows not updating environment variables</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Update Azure Function Environment Variables on Deploy
Result:
- Jira Issue: DEVOPS-513
- Testing environment: [![🚀 Deploy](https://github.com/Andrews-McMeel-Universal/subscription-webhook-manager_function/actions/workflows/deploy.yml/badge.svg?branch=bug%2FDEVOPS-513%2Ftest-functionapp-env-set-workflow)](https://github.com/Andrews-McMeel-Uni …
> [DEVOPS-513] Update Azure Function Environment Variables on Deploy

- .github/workflows/azfunction-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-513" title="DEVOPS-513" target="_blank">DEVOPS-513</a></summary>
<br />
<table>
<tr>
<td>Azure Function deploy workflows not updating environment variables</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix loop that sets key vault references for each environment variable
- Jira Issue: DEVOPS-513
- Testing environment: [![🚀 Deploy](https://github.com/Andrews-McMeel-Universal/gocomics-my-follows-daily-emailer_function/actions/workflows/deploy.yml/badge.svg?branch=bug%2FDEVOPS-513%2Ffix-environment-var-separator)](https://github.com/An …
> [DEVOPS-513] Fix loop that sets key vault references for each environment variable

- .github/workflows/ruby-ci.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-527" title="DEVOPS-527" target="_blank">DEVOPS-527</a></summary>
<br />
<table>
<tr>
<td>Ruby Application CI workflows fail if the app requires gems.amuniversal.com access</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add custom GitHub runner support to Ruby CI workflow
- Jira Issue: DEVOPS-527
> [DEVOPS-527] Add custom GitHub runner support to Ruby CI workflow

- .github/workflows/update-azureapimanagement.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/GOCSERV-119" title="GOCSERV-119" target="_blank">GOCSERV-119</a></summary>
<br />
<table>
<tr>
<td>GoContent Service Down for Double Coconut </td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add productId input so that we can specify custom API keys (for ex. GoContent)
- Jira Issue: GOCSERV-119
> [GOCSERV-119] Add productId input so that we can specify custom API keys (for ex. GoContent)

- .github/workflows/ephemeral-deploy.yaml
- Shorten checksum in Azure Function app name to 18 chars
- Jira Issue: DEVOPS-541
> [DEVOPS-541] Fix failed ephemeral deploys due to app name being too long

- .github/workflows/azfunction-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-550" title="DEVOPS-550" target="_blank">DEVOPS-550</a></summary>
<br />
<table>
<tr>
<td>Azure Function Deploy workflows not using DOTNET_VERSION repository variable</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
…ion Deploy workflow
Fixes this issue: https://github.com/Andrews-McMeel-Universal/subscription-webhook-manager_function/actions/runs/11132827010/job/30937802230
- Default to DOTNET_VERSION repository variable in AzFunction Deploy Workflow
- Jira Issue: DEVOPS-550
> [DEVOPS-550] Default to DOTNET_VERSION repository variable in AzFunction Deploy Workflow

- .github/workflows/azfunction-deploy.yaml
- .github/workflows/dotnet-ci.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-549" title="DEVOPS-549" target="_blank">DEVOPS-549</a></summary>
<br />
<table>
<tr>
<td>Automatically retrieve .NET SDK version from project files for .NET CI tests</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Automatically retrieve .NET version rather than defaulting to workflow input
- Jira Issue: DEVOPS-549
> [DEVOPS-549] Automatically retrieve .NET version rather than defaulting to workflow input

- .github/workflows/aks-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-551" title="DEVOPS-551" target="_blank">DEVOPS-551</a></summary>
<br />
<table>
<tr>
<td>NGINX Kubernetes Ingress Class annotation is being deprecated</td>
</tr>
<tr>
<th>Type</th>
<td>
Maintenance
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fixing NGINX class ingress annotation deprecation warnings
> NOTE: I'm updating the K8s Helm templates to include the new `ingress.ingressClassName` setting in the `values.yaml`. Since this change only uses the value if it's used in the Helm charts, it does not break any deployments if the `values.yaml` file does not have the …
> [DEVOPS-551] Fixing NGINX class ingress annotation deprecation warnings

- .github/workflows/update-azureapimanagement.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-575" title="DEVOPS-575" target="_blank">DEVOPS-575</a></summary>
<br />
<table>
<tr>
<td>Uexpress Service API has "-api" suffix after deploys</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add `apiSuffix` input to API deploy workflow so we can toggle it in cases where the service doesn't need it
- Jira Issue: DEVOPS-575
> [DEVOPS-575] Add `apiSuffix` input to API deploy workflow

- .github/workflows/update-azureapimanagement.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-578" title="DEVOPS-578" target="_blank">DEVOPS-578</a></summary>
<br />
<table>
<tr>
<td>API Deploy fails due to "already exists" conflict error</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add -Force argument to Import command to fix "API.. already exists" errors
- Jira Issue: DEVOPS-578
> [DEVOPS-578] Fix "API already exists" errors

- .github/workflows/update-azureapimanagement.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-579" title="DEVOPS-579" target="_blank">DEVOPS-579</a></summary>
<br />
<table>
<tr>
<td>API deploys are removing the "-api" suffix from the endpoints</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix API suffix not getting added on by default
- Fixed quotes and simplified logic
- Jira Issue: DEVOPS-579
> [DEVOPS-579] Fix API suffix not getting added on by default

- .github/workflows/dotnet-ci.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-602" title="DEVOPS-602" target="_blank">DEVOPS-602</a></summary>
<br />
<table>
<tr>
<td>.NET CI Workflow DOTNET_VERSION input not working</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
<td>To Do</td>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix .NET automatic version resolution
- Check if the `DOTNET_VERSION` input is null before trying to resolve the version automatically. Then use the output of that in the `actions/setup-dotnet` step.
- Jira Issue: DEVOPS-602
> [DEVOPS-602] Fix .NET automatic version resolution

- .github/workflows/aks-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-621" title="DEVOPS-621" target="_blank">DEVOPS-621</a></summary>
<br />
<table>
<tr>
<td>ingressWhitelist is not being set properly during AKS deploys</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
Fix `$ingressWhitelist` being set incorrectly
Basically, the `$ingressWhitelist` variable was being set before the loop so anytime there was a modification made to it during one of the first items in the loop, it would apply those changes to the rest of the ingresses.
- Move setting the `$ingressWhitelist` variable to be inside the loop
- Check to …
> [DEVOPS-621] Fix `$ingressWhitelist` being set incorrectly

- .github/workflows/aks-deploy.yaml
Set ingress whitelists to `$ingressWhitelist` (excluding admin)
- Move setting the ingress whitelist to the end of the loop.
- Set all ingress whitelists' to `$ingressWhitelists`, excluding the `admin-ingress` ingress
- Fix minor issue where the admin ingress `$ingressWhitelist` value was being set unncessarily
> [DEVOPS-XXX] Set ingress whitelists to `$ingressWhitelist` (excluding admin)

- .github/workflows/aks-deploy.yaml
- Add www redirect ingress via deploy workflows (vs having a mostly redundant ingress definition in the Helm templates/values)
- Added logic for also creating a DNS record for the `www.` subdomain instead of just the root hostname
https://test-workflow.centralus.amuniversal.com/ redirects to https://www.test-workflow.centralus.amuniversal.com/
- Jira Issue: DEVOPS-663
- Testing environment: [![🚀 Deploy](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/deploy.yml/badge.svg?branch=story%2FDEVOPS-XXX%2Ffix-www-redirect-in-v2-schema)](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/deploy.yml)
> [DEVOPS-663] Add www redirect ingress via deploy workflows

- .github/workflows/update-azureapimanagement.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-677" title="DEVOPS-677" target="_blank">DEVOPS-677</a></summary>
<br />
<table>
<tr>
<td>API workflows succeeding despite not importing any Swagger JSONs</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
Error out if none of the Swagger JSONs are reachable.
We have had issues the past couple of days where we moved the GitHub runners to a new cluster and the runner IPs changed and were not able to access the Swagger JSONs. The workflows ran successfully despite not importing anything to the Azure APIM instances.
Also a couple of other changes:
- …
> [DEVOPS-677] Error out if none of the Swagger JSONs are reachable

- .github/workflows/update-azureapimanagement.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-686" title="DEVOPS-686" target="_blank">DEVOPS-686</a></summary>
<br />
<table>
<tr>
<td>API Update workflows failing due to DNS updates taking too long</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add multiple retries when pulling in Swagger JSONs so that the workflow doesn't fail immediately when the K8s certs are still being deployed
- Jira Issue: DEVOPS-686
> [DEVOPS-686] Add multiple retries when pulling in Swagger JSONs

- .github/workflows/clear-azure-redis-cache.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-679" title="DEVOPS-679" target="_blank">DEVOPS-679</a></summary>
<br />
<table>
<tr>
<td>Add multi-key support to Purge Redis caches workflow</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
…rkflow
- Add multi-key support in the Clear Azure Redis Caches workflow
Inputs:
- `$CacheKeys = "GC-Subscription*,TPS-Subscription*"`
- `$ResourceGroupName = "AMU_DevOps_RG"`
- `$Environment = "staging"`
Result:
- Jira Issue: DEVOPS-679
> [DEVOPS-679] Add multi-key support in the Clear Azure Redis Caches workflow

- .github/workflows/aks-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-676" title="DEVOPS-676" target="_blank">DEVOPS-676</a></summary>
<br />
<table>
<tr>
<td>Switch to official Docker GitHub actions in AKS deploy workflow</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Switch to official Docker GitHub actions in AKS deploy workflow instead of manually running the `docker tag` and `docker build` commands
- Jira Issue: DEVOPS-676
- Testing environment: [![🚀 Deploy](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/deploy.yml/badge.svg?branch=story%2FDEVOPS-676%2Fdocker-gith …
> [DEVOPS-676] Switch to official Docker GitHub actions in AKS deploy workflow

- .github/workflows/ephemeral-deploy.yaml
- .github/workflows/jira-lint.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-694" title="DEVOPS-694" target="_blank">DEVOPS-694</a></summary>
<br />
<table>
<tr>
<td>Ephemeral Deployment Workflow Not Parsing Jira Issue Key from PR Details</td>
</tr>
<tr>
<th>Type</th>
<td>
Bug
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Fix accidental command evaluation in PR description
- Jira Issue: DEVOPS-694
> [DEVOPS-694] Fix accidental command evaluation in PR description

- .github/workflows/next-ci.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-700" title="DEVOPS-700" target="_blank">DEVOPS-700</a></summary>
<br />
<table>
<tr>
<td>Allow CI actions to access staging/dev game endpoints for GC UI</td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
- Add support for custom GitHub Runner in Next CI workflows
- Jira Issue: DEVOPS-700
> [DEVOPS-700] Add support for custom GitHub Runner in Next CI workflows

- .github/workflows/aks-deploy.yaml
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-643" title="DEVOPS-643" target="_blank">DEVOPS-643</a></summary>
<br />
<table>
<tr>
<td>Add Helm template support for HA datacenters to be used with Azure Front Doors </td>
</tr>
<tr>
<th>Type</th>
<td>
Story
</td>
</tr>
<tr>
</tr>
<tr>
<td>N/A</td>
</tr>
<tr>
<td>-</td>
</tr>
</table>
</details>
---
We have sites that have their primary datacenter location hardcoded in their K8s ingress hostname (their respective `values.yaml` file), for example "development.centralus.gocomics.com". 
These changes are to add support using a repository variable to toggle automatically adding in the datacenter location of the …
> [DEVOPS-643] New input for adding HA datacenter to the K8s ingress
